# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cf3ed319da5e46b5c2fb1e92fb0071b020805c57d20f5c97207598ca74ee89aad31f9e7438aff4b9dfaea0527afdfbef935c597b23710ba5f1eecb788c047343

test:
  secret_key_base: 0e19b72c1ef62bdbfd13eb0dfa94b3a752e2ea6deae27e56a10a3bc13c9ac401b6206ba94ee1c435b05aa65141ad2287952cff404865a9f6a36a168235c5e0ff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
